# Generated by Django 3.1.1 on 2021-03-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultiSel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionID', models.IntegerField(max_length=10, verbose_name='题目编号')),
                ('Question', models.TextField(verbose_name='题目内容')),
                ('ChoiceA', models.TextField(verbose_name='选项A')),
                ('ChoiceB', models.TextField(verbose_name='选项B')),
                ('ChoiceC', models.TextField(verbose_name='选项C')),
                ('ChoiceD', models.TextField(verbose_name='选项D')),
                ('Answer', models.CharField(max_length=5, verbose_name='参考答案')),
                ('Score', models.IntegerField(default=2, verbose_name='题目分值')),
            ],
            options={
                'verbose_name': '多选题',
                'verbose_name_plural': '多选题',
            },
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaperSerial', models.IntegerField(default=0, verbose_name='试卷中题目编号')),
                ('QuestionID', models.IntegerField(max_length=10, verbose_name='试题原编号')),
                ('QuestionType', models.CharField(choices=[('single', '单选题'), ('multiple', '多选题'), ('rorw', '判断题')], max_length=20, verbose_name='试题类型')),
                ('UserAnswer', models.CharField(max_length=5, null=True, verbose_name='学生答案')),
                ('Score', models.IntegerField(default=2, max_length=5, verbose_name='题目分值')),
                ('Commence', models.IntegerField(max_length=5, verbose_name='系统评分')),
            ],
            options={
                'verbose_name': '试卷信息',
                'verbose_name_plural': '试卷信息',
            },
        ),
        migrations.CreateModel(
            name='RightOrWrong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionID', models.IntegerField(max_length=10, verbose_name='题目编号')),
                ('Question', models.TextField(verbose_name='题目内容')),
                ('Answer', models.CharField(max_length=5, verbose_name='参考答案')),
                ('Score', models.IntegerField(default=2, verbose_name='题目分值')),
            ],
            options={
                'verbose_name': '判断题',
                'verbose_name_plural': '判断题',
            },
        ),
        migrations.CreateModel(
            name='SingleSel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionID', models.IntegerField(max_length=10, verbose_name='题目编号')),
                ('Question', models.TextField(verbose_name='题目内容')),
                ('ChoiceA', models.TextField(verbose_name='选项A')),
                ('ChoiceB', models.TextField(verbose_name='选项B')),
                ('ChoiceC', models.TextField(verbose_name='选项C')),
                ('ChoiceD', models.TextField(verbose_name='选项D')),
                ('Answer', models.CharField(max_length=5, verbose_name='参考答案')),
                ('Score', models.IntegerField(default=2, verbose_name='题目分值')),
            ],
            options={
                'verbose_name': '选择题',
                'verbose_name_plural': '选择题',
            },
        ),
    ]
