# Generated by Django 3.1.1 on 2021-03-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotexam', '0002_auto_20210316_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multisel',
            name='QuestionImage',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/%Y/%m', verbose_name='题目图片'),
        ),
        migrations.AlterField(
            model_name='rightorwrong',
            name='QuestionImage',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/%Y/%m', verbose_name='题目图片'),
        ),
        migrations.AlterField(
            model_name='singlesel',
            name='QuestionImage',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/%Y/%m', verbose_name='题目图片'),
        ),
    ]
