# Generated by Django 3.1.1 on 2021-03-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotexam', '0003_auto_20210316_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='multisel',
            name='QuestionDate',
            field=models.IntegerField(default=20210316, max_length=10, verbose_name='试题日期'),
        ),
        migrations.AddField(
            model_name='rightorwrong',
            name='QuestionDate',
            field=models.IntegerField(default=20210316, max_length=10, verbose_name='试题日期'),
        ),
        migrations.AddField(
            model_name='singlesel',
            name='QuestionDate',
            field=models.IntegerField(default=20210316, max_length=10, verbose_name='试题日期'),
        ),
    ]
