# Generated by Django 3.1.1 on 2021-03-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotexam', '0005_auto_20210316_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multisel',
            name='QuestionDate',
            field=models.IntegerField(default=20210316, verbose_name='试题日期'),
        ),
        migrations.AlterField(
            model_name='multisel',
            name='QuestionID',
            field=models.IntegerField(null=True, verbose_name='题目编号'),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='Commence',
            field=models.IntegerField(verbose_name='系统评分'),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='QuestionID',
            field=models.IntegerField(verbose_name='试题原编号'),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='Score',
            field=models.IntegerField(default=2, verbose_name='题目分值'),
        ),
        migrations.AlterField(
            model_name='rightorwrong',
            name='QuestionDate',
            field=models.IntegerField(default=20210316, verbose_name='试题日期'),
        ),
        migrations.AlterField(
            model_name='rightorwrong',
            name='QuestionID',
            field=models.IntegerField(null=True, verbose_name='题目编号'),
        ),
        migrations.AlterField(
            model_name='singlesel',
            name='QuestionDate',
            field=models.IntegerField(default=20210316, verbose_name='试题日期'),
        ),
        migrations.AlterField(
            model_name='singlesel',
            name='QuestionID',
            field=models.IntegerField(null=True, verbose_name='题目编号'),
        ),
    ]
