# Generated by Django 3.1.1 on 2021-03-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotexam', '0006_auto_20210317_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multisel',
            name='Score',
            field=models.IntegerField(default=2, verbose_name='题目分值'),
        ),
        migrations.AlterField(
            model_name='rightorwrong',
            name='Score',
            field=models.IntegerField(default=2, verbose_name='题目分值'),
        ),
        migrations.AlterField(
            model_name='singlesel',
            name='Score',
            field=models.IntegerField(default=4, verbose_name='题目分值'),
        ),
    ]
