# Generated by Django 3.1.1 on 2021-03-24 15:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robotexam', '0008_auto_20210317_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=8, verbose_name='性别')),
                ('password', models.CharField(default='12345678', max_length=20, verbose_name='密码')),
                ('birthday', models.DateField(verbose_name='出生日期')),
                ('email', models.EmailField(default=None, max_length=254, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=8, verbose_name='性别')),
                ('password', models.CharField(default='111111', max_length=20, verbose_name='密码')),
                ('email', models.EmailField(default=None, max_length=254, verbose_name='邮箱')),
                ('birthday', models.DateField(verbose_name='出生日期')),
            ],
            options={
                'verbose_name': '教师信息',
                'verbose_name_plural': '教师信息',
                'db_table': 'teacher',
            },
        ),
        migrations.AlterModelTable(
            name='multisel',
            table='multisel',
        ),
        migrations.AlterModelTable(
            name='questionpaper',
            table='questionpaper',
        ),
        migrations.AlterModelTable(
            name='rightorwrong',
            table='row',
        ),
        migrations.AlterModelTable(
            name='singlesel',
            table='singlesel',
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GradeDate', models.DateField(default=datetime.datetime.now, verbose_name='成绩')),
                ('grade', models.IntegerField(verbose_name='成绩')),
                ('sid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='robotexam.student')),
            ],
            options={
                'verbose_name': '成绩',
                'verbose_name_plural': '成绩',
                'db_table': 'grade',
            },
        ),
    ]
