# Generated by Django 3.1.1 on 2021-03-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotexam', '0009_auto_20210324_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=5, verbose_name='学生答案')),
            ],
        ),
    ]
