# Generated by Django 3.1.1 on 2021-03-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotexam', '0010_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlesel',
            name='QuestionImage',
            field=models.ImageField(blank=True, null=True, upload_to='static/question_images/%Y/%m', verbose_name='题目图片'),
        ),
    ]
