# Generated by Django 3.1.1 on 2021-03-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotexam', '0011_auto_20210325_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multisel',
            name='QuestionImage',
            field=models.ImageField(blank=True, null=True, upload_to='static/question_images/%Y/%m', verbose_name='题目图片'),
        ),
        migrations.AlterField(
            model_name='rightorwrong',
            name='QuestionImage',
            field=models.ImageField(blank=True, null=True, upload_to='static/question_images/%Y/%m', verbose_name='题目图片'),
        ),
    ]
