# Generated by Django 3.1.1 on 2021-03-18 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='message',
            table='message',
        ),
    ]
